services:
  - type: web
    name: skribbl-clone
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: skribbl-clone-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: skribbl-clone-db
    databaseName: skribbl_clone
    user: skribbl_clone_user
    plan: free
